version: '3'

services:
  app:
    image: stationSki-1.1.4/stationski
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - db
    volumes:
      - .m2:/root/.m2

volumes:
  .m2: