version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
    volumes:
      - .m2:/root/.m2
    networks:
      springboot-mysql-net:
  app:
    image: stationSki-1.1.5/stationski
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    volumes:
      - db:/var/lib/mysql
    networks:
      springboot-mysql-net:
    restart: on-failure
networks:
  springboot-mysql-net:
volumes:
  db:
  .m2: