version: '3'

services:
  app:
    image: ibrahimbenkhalifa/stationski
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - db
    volumes:
      - .m2:/root/.m2

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    container_name: mysql_comp
    volumes:
      - /path/to/mysql/data:/var/lib/mysql
      - /path/to/mysql/conf:/etc/mysql/conf.d



volumes:
  .m2:   # This should be a named volume, not a path
  db:    # This should be a named volume, not an empty definition
