version: '3.8'

services:
  app:
    image: ibrahimbenkhalifa/stationski
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8089:8089
    depends_on:
      - db
    volumes:
      - .m2:/root/.m2

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    container_name: mysql_comp
    volumes:
      - /path/to/mysql/data:/var/lib/mysql
      - /path/to/mysql/conf:/etc/mysql/conf.d
