version: "3"

services:
  app:
    image: stationSki-1.1.5/stationski
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  .m2:

