version: "3.8"
services:
 gestion-station-ski:
     depends_on:
       - mysqldb
     image: ibrahimbenkhalifa/stationski
     restart: on-failure
     environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/stationSki
       SPRING_DATASOURCE_USERNAME: root
       SPRING_DATASOURCE_PASSWORD: 123456
     ports:
       - "8089:8089"
     stdin_open: true
     tty: true
     volumes:
       - .m2:/root/.m2

 db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    container_name: mysql_comp
    volumes:
      - /path/to/mysql/data:/var/lib/mysql
      - /path/to/mysql/conf:/etc/mysql/conf.d

 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8084:80"
    container_name: phpmyadmin_comp
    depends_on:
         - db

volumes:
  db:
  .m2:
