version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  angular-app:
    build:
      context: ./
    image: ibrahimbenkhalifa/stationskiangular
    ports:
      - "4200:4200"
    depends_on:
      - gestion-station-ski

  gestion-station-ski:
    depends_on:
      - mysqldb
    image: ibrahimbenkhalifa/stationski
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "8089:8089"
    stdin_open: true
    tty: true

volumes:
  db:
