version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  gestion-station-ski:
    depends_on:
      - mysqldb
    image: ibrahimbenkhalifa/stationski
    restart: on-failure
    environment:
      MYSQL_ROOT_USERNAME: "root"

      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "8089:8089"
    stdin_open: true
    tty: true

    volumes:
      - .m2:/root/.m2

  phpmyadmin :
    image: phpmyadmin/phpmyadmin
    ports:
      - "8084:80"
    container_name: phpmyadmin_comp
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: mysqldb


volumes:
  db:
  .m2: