version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  gestion-station-ski:
    depends_on:
      - mysqldb
    image: ibrahimbenkhalifa/stationski

    environment:
      MYSQL_ROOT_PASSWORD: ""  # Set to an empty string
    ports:
      - "8089:8089"
    stdin_open: true
    tty: true

volumes:
  db: