version: "3.8"
services:
  mysqldb:
    build:
      context: ./
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  angular-app:
    build:
      context: ./
    image: ibrahimbenkhalifa/stationskiangular
    ports:
      - "4200:4200"
    depends_on:
      - stationski
  stationski:
    build:
      context: .
    image: ibrahimbenkhalifa/stationski
    container_name: ibrahimbenkhalifa/stationski
    ports:
      - "8089:8089"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:
  mysql_config:

