#FROM openjdk:11-jdk-slim
#EXPOSE 8089
#ADD target/stationSki-1.2.5.jar docker-spring-boot.jar
#ENTRYPOINT ["java","-jar","/docker-spring-boot.jar"]
FROM openjdk:11-jre-slim
VOLUME /tmp
ARG JAR_FILE=target/stationSki-1.2.5.jar.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
