version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123456"  # Set your desired root password here
      MYSQL_DATABASE: your_database_name
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  gestion-station-ski:
    depends_on:
      - mysqldb
    image: ibrahimbenkhalifa/stationski
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/your_database_name
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456  # Set your MySQL root password here
    ports:
      - "8089:8089"
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8084:80"
    container_name: phpmyadmin_comp
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_USER: root
      PMA_PASSWORD: 123456  # Set your MySQL root password here

volumes:
  db:
  .m2:
