version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /path/to/mysql/data:/var/lib/mysql
      - /path/to/mysql/conf:/etc/mysql/conf.d
    restart: always
    depends_on:
      - db
  app:
    image: mohsenfennnira/stationski
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    volumes:
      - .m2:/root/.m2

    restart: on-failure
volumes:
  db:
  .m2: